name: PaperPing
version: '0.1.0'
main: io.github.woundedkoba.paperping.PaperPing
api-version: '1.21.7'
authors: [xDefcon, woundedkoba]
description: >
  PaperPing is a simple and customizable plugin to show your ping.
commands:
    ping:
      description: The main command for PaperPing.
    pingreload:
      description: Reloads the plugin.
